 language: python

 python: "3.6"

 # don't clone more than necessary
 git:
   depth: 1

 # Install dependencies
 install:
   - pip install -r requirements.txt

 # script to run tests. Script can have many commands, one per line.
 script:
   - manage.py makemigrations
   - manage.py migrate
   - coverage run --source='.' manage.py test game/tests

 after_success:
   - codecov