 language: python

 python: "3.6"

 # don't clone more than necessary
 git:
   depth: 1

 # Install dependencies
 install:
   - pip install -r requirements.txt

 before_script:
    - wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
    - export CHROME_BIN=chromium-browser

 # script to run tests. Script can have many commands, one per line.
 script:
   - python manage.py makemigrations
   - python manage.py migrate
   - coverage run manage.py test game/tests/
   - coverage xml --omit=mysite/*,game/migrations/*,manage.py

 after_success:
   - codecov