 language: python

 python: "3.6"

 # don't clone more than necessary
 git:
   depth: 1

 # Install dependencies
 install:
   - pip install -r requirements.txt

 addons:
   chrome: stable
   apt:
     packages:
       - chromium-chromedriver

 before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

 # script to run tests. Script can have many commands, one per line.
 script:
   - python manage.py makemigrations
   - python manage.py migrate
   - coverage run manage.py test game/tests/
   - coverage xml --omit=mysite/*,game/migrations/*,manage.py

 after_success:
   - codecov